# Generated by Django 3.1.7 on 2021-04-22 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='number')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница')], max_length=15, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='department name')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='doctor surname')),
                ('name', models.CharField(max_length=50, verbose_name='doctor name')),
                ('patronymic', models.CharField(max_length=50, verbose_name='doctor patronymic')),
                ('position', models.CharField(max_length=50, verbose_name='doctor position')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cabinet', verbose_name='cabinet')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='patient surname')),
                ('name', models.CharField(max_length=50, verbose_name='patient name')),
                ('patronymic', models.CharField(max_length=50, verbose_name='patient patronymic')),
                ('login', models.CharField(max_length=100, verbose_name='login')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('policy', models.CharField(max_length=20, verbose_name='policy')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('date', models.DateField()),
                ('number', models.CharField(max_length=20, verbose_name='number')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.day', verbose_name='day of week')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doctor', verbose_name='cabinet')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.timetable')),
            ],
        ),
        migrations.AddField(
            model_name='cabinet',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.department', verbose_name='department'),
        ),
    ]
